# Generated by Django 4.2.8 on 2023-12-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
